name: Tests

on:
    - push
    - pull_request

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - name: Install dependencies
              shell: bash
              run: pnpm --filter lib install --frozen-lockfile
            - name: Run cypress tests
              shell: bash
              run: pnpm --filter lib test-cli:electron
